import { readdir } from "node:fs/promises";
import { join } from "node:path";

const COMMANDS_DIR = join(process.cwd(), "src/commands");
const INDEX_FILE = join(COMMANDS_DIR, "index.ts");

console.log(`🤖 Generating command registry in ${COMMANDS_DIR}...`);

async function generate() {
  const files = await readdir(COMMANDS_DIR);

  const exports = files
    .filter(
      (f: string) =>
        f.endsWith(".ts") && f !== "index.ts" && !f.endsWith(".d.ts"),
    )
    .map((f: string) => `export * from "./${f.replace(".ts", ".js")}";`)
    .sort()
    .join("\n");

  const content = `// 🤖 AUTO-GENERATED BY scripts/generate-registry.ts\n// DO NOT EDIT MANUALLY\n\n${exports}\n`;

  await Bun.write(INDEX_FILE, content);
  console.log(
    `✅ Registry updated with ${exports.split("\n").length} commands.`,
  );
}

generate().catch(console.error);
